name: repoviewer
description: A Github Client Application.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.19.1 <3.0.0'

dependencies:
    auto_route: ^5.0.4
    dio: ^5.0.0
    flash: ^2.0.5+1
    flutter:
        sdk: flutter
    flutter_hooks: ^0.18.5+1
    flutter_secure_storage: ^8.0.0
    freezed_annotation: ^2.2.0
    hooks_riverpod: ^2.2.0
    oauth2: ^2.0.1
    webview_flutter: ^4.0.2

dev_dependencies:
    auto_route_generator: ^5.0.3
    build_runner: ^2.3.3
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.3.2

flutter:
    uses-material-design: true
