name: repoviewer
description: A Github Client Application.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.19.1 <3.0.0'

dependencies:
    auto_route: ^5.0.4
    dartz: ^0.10.1
    dio: ^5.0.0
    flash: ^2.0.5+1
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.0.2
    flutter_hooks: ^0.18.5+1
    flutter_secure_storage: ^8.0.0
    fpdart: ^0.4.0
    freezed_annotation: ^2.2.0
    google_fonts: ^4.0.3
    json_annotation: ^4.8.0
    hooks_riverpod: ^2.2.0
    http: ^0.13.5
    material_design_icons_flutter: ^6.0.7096
    oauth2: ^2.0.1
    webview_flutter: ^4.0.2
    sembast: ^3.4.0+6
    json_serializable: ^6.6.1
    path_provider: ^2.0.13
    path: ^1.8.2

dev_dependencies:
    auto_route_generator: ^5.0.3
    build_runner: ^2.3.3
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.3.2

flutter:
    uses-material-design: true
    assets:
        - .env
